FROM mcr.microsoft.com/dotnet/sdk:6.0.400-bullseye-slim AS base

FROM base AS build
ENV NODE_VERSION 16.16.0
ENV NODE_DOWNLOAD_SHA c85b16d1a4c259d01be7111ecb0361260627e4fc245004a920521eacb28e50df
RUN curl -SL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz" --output nodejs.tar.gz \
    && echo "$NODE_DOWNLOAD_SHA  nodejs.tar.gz" | sha256sum -c - \
    && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && npm install --global grunt-cli@1.4.3

FROM base AS final
COPY --from=build /usr/local/bin /usr/local/bin
COPY --from=build /usr/local/include /usr/local/include
COPY --from=build /usr/local/lib /usr/local/lib
COPY --from=build /usr/local/share /usr/local/share
COPY --from=build /root/.npm /root/.npm
