FROM mcr.microsoft.com/dotnet/sdk:5.0.100-rc.1-alpine3.12 AS base

FROM base AS build
ENV NODE_VERSION 12.19.0
ENV NODE_DOWNLOAD_SHA a268c72e8b9b0028d0e064c9a5684b279987e15d00feb7128ba6707d3d8e8857
RUN curl -SL "https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64-musl.tar.gz" --output nodejs.tar.gz \
    && echo "$NODE_DOWNLOAD_SHA  nodejs.tar.gz" | sha256sum -c - \
    && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 --no-same-owner \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && npm install --global grunt-cli@1.3.2

FROM base AS final
COPY --from=build /usr/local/bin /usr/local/bin
COPY --from=build /usr/local/include /usr/local/include
COPY --from=build /usr/local/lib /usr/local/lib
COPY --from=build /usr/local/share /usr/local/share
COPY --from=build /root/.npm /root/.npm
